using System.Reflection;

namespace Squeel;

internal static class GeneratedFileOptions
{
    public static readonly Version Version = typeof(GeneratedFileOptions).Assembly.GetName().Version;

    public static readonly string Header = $"""
        // <auto-generated>
        //   This file was generated by the source generator Squeel
        //   
        //   Version      {Version}
        //   SHA          {typeof(GeneratedFileOptions).Assembly.GetCustomAttribute<AssemblyMetadataAttribute>()?.Value}
        //   Repository   https://github.com/S-E-F/Squeel
        // </auto-generated>
        """;

    public static readonly string Attribute = $"""
        [global::System.CodeDom.Compiler.GeneratedCode("Squeel", "{Version}")]
        """;

    public const string Namespace = "Squeel";

    public const string MethodName = "QueryAsync";

    public const string MethodMetadataSignature
        = $"System.Threading.Tasks.Task`1 {Namespace}.SqueelDbConnectionExtensions.{MethodName}`1(Npgsql.NpgsqlConnection, ref {Namespace}.SqueelInterpolatedStringHandler, System.Threading.CancellationToken)";
}
